/**
 * Turn a natural-language question (or a bare statement) into a handful of
 * content keywords used to pull candidate records out of the database.
 *
 * Deliberately dumb — no stemming, no embeddings. The LLM does the reasoning;
 * this only has to cast a wide-enough net that the relevant rows are in the
 * context window. Accents are preserved in the returned terms because Postgres
 * `contains` + `mode: "insensitive"` folds case but NOT diacritics — matching
 * "réunion" requires searching for "réunion", not "reunion".
 */

/** Words that carry no retrieval signal. Stored unaccented; see `deaccent`. */
const STOPWORDS = new Set([
  // French
  "le",
  "la",
  "les",
  "un",
  "une",
  "des",
  "de",
  "du",
  "au",
  "aux",
  "et",
  "ou",
  "mais",
  "donc",
  "ni",
  "car",
  "que",
  "qui",
  "quoi",
  "dont",
  "ce",
  "cet",
  "cette",
  "ces",
  "mon",
  "ma",
  "mes",
  "ton",
  "ta",
  "tes",
  "son",
  "sa",
  "ses",
  "notre",
  "nos",
  "votre",
  "vos",
  "leur",
  "leurs",
  "je",
  "tu",
  "il",
  "elle",
  "on",
  "nous",
  "vous",
  "ils",
  "elles",
  "me",
  "te",
  "se",
  "moi",
  "toi",
  "lui",
  "en",
  "pour",
  "par",
  "sur",
  "sous",
  "dans",
  "avec",
  "sans",
  "chez",
  "vers",
  "entre",
  "est",
  "sont",
  "etait",
  "etaient",
  "ete",
  "etre",
  "suis",
  "sommes",
  "etes",
  "ai",
  "as",
  "avons",
  "avez",
  "ont",
  "avait",
  "avaient",
  "avoir",
  "fait",
  "faire",
  "quel",
  "quelle",
  "quels",
  "quelles",
  "quand",
  "comment",
  "pourquoi",
  "combien",
  "est-ce",
  "plus",
  "moins",
  "tres",
  "tout",
  "tous",
  "toute",
  "toutes",
  "meme",
  "aussi",
  "bien",
  "deja",
  "encore",
  "si",
  "ne",
  "pas",
  "non",
  "oui",
  "y",
  "des",
  "cela",
  "ca",
  "voila",
  "alors",
  "dis",
  "dit",
  "donne",
  "montre",
  "trouve",
  "cherche",
  "peux",
  "peut",
  "veux",
  "veut",
  "dois",
  "doit",
  "faut",
  // English
  "the",
  "a",
  "an",
  "and",
  "or",
  "but",
  "so",
  "of",
  "in",
  "on",
  "at",
  "to",
  "for",
  "with",
  "without",
  "from",
  "by",
  "about",
  "as",
  "is",
  "are",
  "was",
  "were",
  "be",
  "been",
  "being",
  "do",
  "does",
  "did",
  "doing",
  "have",
  "has",
  "had",
  "what",
  "which",
  "who",
  "whom",
  "whose",
  "when",
  "where",
  "why",
  "how",
  "all",
  "any",
  "both",
  "each",
  "few",
  "more",
  "most",
  "some",
  "such",
  "no",
  "nor",
  "not",
  "only",
  "own",
  "same",
  "than",
  "too",
  "very",
  "can",
  "will",
  "just",
  "should",
  "now",
  "i",
  "me",
  "my",
  "we",
  "our",
  "you",
  "your",
  "he",
  "she",
  "it",
  "they",
  "them",
  "this",
  "that",
  "these",
  "those",
  "there",
  "here",
  "get",
  "got",
  "show",
  "tell",
  "find",
  "give",
  "need",
  "want",
  "would",
  "could",
  "please",
]);

/** Strip diacritics — used only to test membership in STOPWORDS. */
function deaccent(word: string): string {
  return word.normalize("NFD").replace(/\p{Diacritic}/gu, "");
}

const MAX_TERMS = 10;

/**
 * Extract up to {@link MAX_TERMS} search terms, longest first so the most
 * distinctive words survive the cap. Returns `[]` for questions made entirely
 * of stopwords ("what do I have today?") — callers must still fall back to
 * recency-based retrieval in that case.
 */
export function extractKeywords(question: string): string[] {
  const seen = new Set<string>();
  const terms: string[] = [];

  for (const raw of question.toLowerCase().split(/[^\p{L}\p{N}]+/u)) {
    if (!raw) continue;
    const bare = deaccent(raw);
    if (STOPWORDS.has(bare)) continue;
    // Short tokens are noise, except 4-digit numbers (years like "2026").
    const isYear = /^\d{4}$/.test(raw);
    if (!isYear && raw.length < 3) continue;
    if (seen.has(raw)) continue;
    seen.add(raw);
    terms.push(raw);
  }

  return terms.sort((a, b) => b.length - a.length).slice(0, MAX_TERMS);
}
