-- AlterTable
ALTER TABLE "TaxProfile" ADD COLUMN     "accountant" TEXT,
ADD COLUMN     "accountantEmail" TEXT,
ADD COLUMN     "accountantPhone" TEXT,
ADD COLUMN     "activity" TEXT,
ADD COLUMN     "address" TEXT,
ADD COLUMN     "bank" TEXT,
ADD COLUMN     "businessNumber" TEXT,
ADD COLUMN     "city" TEXT,
ADD COLUMN     "email" TEXT,
ADD COLUMN     "legalName" TEXT,
ADD COLUMN     "naicsCode" TEXT,
ADD COLUMN     "neq" TEXT,
ADD COLUMN     "partnerShares" DOUBLE PRECISION[] DEFAULT ARRAY[]::DOUBLE PRECISION[],
ADD COLUMN     "phone" TEXT,
ADD COLUMN     "postalCode" TEXT,
ADD COLUMN     "province" TEXT NOT NULL DEFAULT 'QC',
ADD COLUMN     "startedAt" TIMESTAMP(3),
ADD COLUMN     "website" TEXT;
